#ifndef BAIYSFJKUUJNXEUGXUSYEAKTSXVDAUTHXYSVRVQPBNMFCYFNTBAWSSGTCJGWMNTFTUBSBVBJA
#define BAIYSFJKUUJNXEUGXUSYEAKTSXVDAUTHXYSVRVQPBNMFCYFNTBAWSSGTCJGWMNTFTUBSBVBJA

#include "../includes.hpp"

namespace ceras
{

    template< typename T >
    concept arithmetic = std::is_arithmetic_v<T>;


}//namespace ceras

#endif//BAIYSFJKUUJNXEUGXUSYEAKTSXVDAUTHXYSVRVQPBNMFCYFNTBAWSSGTCJGWMNTFTUBSBVBJA
