#ifndef TMISXBJJVDKPBOVVELQDKQVKPQLTYCLXOYATMOIYGJMALMXVHTMOIRJUWJREOTBWVBCADIXIE
#define TMISXBJJVDKPBOVVELQDKQVKPQLTYCLXOYATMOIYGJMALMXVHTMOIRJUWJREOTBWVBCADIXIE

#include "../utils/string.hpp"

namespace Keras
{
    template< ceras::string Name >
    struct constraint
    {
        //TODO:
    };
}//namespace Keras

#endif//TMISXBJJVDKPBOVVELQDKQVKPQLTYCLXOYATMOIYGJMALMXVHTMOIRJUWJREOTBWVBCADIXIE

