#ifndef PEYUCJHIVVYQUVOMNDHVHKEVHNNKMKPCYQUGYFIERJFDYDEQRSVWPRKMEIYUJBAQDPLRVKIWL
#define PEYUCJHIVVYQUVOMNDHVHKEVHNNKMKPCYQUGYFIERJFDYDEQRSVWPRKMEIYUJBAQDPLRVKIWL

// constraint is yet another indirect layer

namespace ceras::keras
{

}//namespace ceras::keras

#endif//PEYUCJHIVVYQUVOMNDHVHKEVHNNKMKPCYQUGYFIERJFDYDEQRSVWPRKMEIYUJBAQDPLRVKIWL

