#ifndef UDKCKNFPFKBKKKKEHMHEGIXXGPWJVIFXKYALFWIPNXAGYBEDTHDYTWCVSLBYHIGOWCKELJYDS
#define UDKCKNFPFKBKKKKEHMHEGIXXGPWJVIFXKYALFWIPNXAGYBEDTHDYTWCVSLBYHIGOWCKELJYDS

#include "../utils/string.hpp"

namespace Keras
{

    template< ceras::string Name >
    struct regularizer
    {
        // TODO:
    };

}//namespace Keras

#endif//UDKCKNFPFKBKKKKEHMHEGIXXGPWJVIFXKYALFWIPNXAGYBEDTHDYTWCVSLBYHIGOWCKELJYDS

