name: Auto-Release on Tag
on:
  push:
    tags:
      - 'v*'
    branches: [ master ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    steps:
    - name: Get the version
      id: get_version
      run: echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false

  build-ubuntu:
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Package project
      run: zip -r ceras include dataset
    - name: Upload Release Asset
      id: upload-release-asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ./ceras.zip
        asset_name: ceras-${{ needs.create-release.outputs.version }}.zip
        asset_content_type: application/zip

