name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 12
        platform: x64
    - name: make test CI
      run: make CXX=g++-12 ci && ./bin/test_ci
    - name: make mnist_minimal
      run: make CXX=g++-12 mnist_minimal && ./bin/test_mnist_minimal

